### ISSUE TITLE
It is crashing when I'm trying multiple permission.

### ISSUE THREAD

**Issue by asnagni** [vinodbaste/permission_handler#1]
I looks like some instructions are missing in you documentation.
When I'm trying to have multiple permission, the library will crash with the output:

    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.alainsergenagni.bebetter, PID: 27841
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.alainsergenagni.bebetter/com.library.permission_handler.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2171)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
        at android.app.Activity.startActivityForResult(Activity.java:5583)
        at android.app.Activity.startActivityForResult(Activity.java:5541)
        at android.app.Activity.startActivity(Activity.java:6039)
        at android.app.Activity.startActivity(Activity.java:6006)
        at com.library.permission_handler.PermissionsHandler.requestPermission(PermissionsHandler.java:121)
        at com.library.permission_handler.PermissionsHandler.requestPermission(PermissionsHandler.java:52)
        at org.cocos2dx.cpp.AppActivity.showCameraOnUI(AppActivity.java:1622)
        at org.cocos2dx.cpp.AppActivity$8.run(AppActivity.java:1608)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8741)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process: Sending signal. PID: 27841 SIG: 9

**Comment by asnagni** [comment]
This is the code:

        String[] permissions = {Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE};
        PermissionsHandler.requestPermission(m_context/*context*/, String.valueOf(permissions), null/*rationale*/, new  PermissionHandler()
        {
            @Override
            public void onPermissionGranted()
            {

            }

            @Override
            public void onPermissionDenied(Context context, ArrayList<String> deniedPermissions)
            {

            }
        });

**Comment by asnagni** [comment]
Fixed, I just need to add this in the Manifest file:
<activity android:name="com.library.permission_handler.PermissionsActivity"></activity>
